language: ruby
rvm:
- 3.0.1
node_js:
- 15
services:
- postgresql
- redis
addons:
  postgresql: "12"
  apt:
    packages:
    - postgresql-12
    - postgresql-client-12
before_install:
# RUBYGEMS
- gem update --system
- gem install bundler
install: bundle install --jobs=3 --retry=3
before_script:
# POSTGRESQL
- createuser greenie
- createdb -O greenie greenie_test
# SEED
- bundle exec rails db:migrate
env:
  global:
  - RAILS_TEST_DB_USERNAME=travis
  - PGUSER=travis
  - PGPORT=5433
  - PATH="$HOME/bin:$PATH"
script:
- rspec spec
