shared:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
  username: greenie

development:
  database: greenie_development

test: &test
  host: localhost
  username: <%= ENV.fetch('POSTGRES_USER') { 'tmorgan' } %>
  owner: greenie
  password: <%= ENV.fetch('POSTGRES_PASSWORD') { '' } %>
  database: <%= ENV.fetch('POSTGRES_DB') { 'greenie_test' } %>

cypress: *test

production:
  database: greenie_production
