name: Deploy

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Runs when CI passes
  workflow_run:
    workflows: [CI]
    branches: [master]
    types: [completed]

# Allow one concurrent deployment
concurrency:
  group: pages
  cancel-in-progress: true

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  deploy:
      name: Deploy to Fly.io
      if: ${{ github.event.workflow_run.conclusion == 'success' }}
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
          with:
            fetch-depth: 0
        - name: Set up flyctl
          uses: superfly/flyctl-actions/setup-flyctl@master
        - name: Deploy to Fly.io
          run: flyctl deploy --remote-only
        - name: Create Sentry release
          uses: getsentry/action-release@v3
          env:
            SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
            SENTRY_ORG: timcodes
            SENTRY_PROJECT: greenie-backend
          with:
            environment: production
